---
- name: Installing Tomcat
  hosts: nodes
  become: yes
  gather_facts: yes

  tasks:
  # --- 1. OS Specific Java Installation ---
    - name: Install Java on Debian
      ansible.builtin.apt:
        name: "{{ java_package_name }}"
        state: present
        update_cache: yes
      when: ansible_facts.os_family == "Debian"

    - name: Install Java on RedHat
      ansible.builtin.package:
        name: "{{ java_package_name }}"
        state: present
      when: ansible_facts.os_family == "RedHat"

  # --- 2. User and Group Setup ---
    - name: Create tomcat user
      ansible.builtin.user:
        name: "{{ user_name }}"
        home: "{{ user_home }}"
        shell: "{{ user_shell }}"
        create_home: yes
        state: present

  # --- 3. Check Tomcat Installation ---
    - name: Check if Tomcat already extracted
      ansible.builtin.stat:
        path: "{{ user_home }}/bin/startup.sh"
      register: tomcat_status

  # --- 4. Download and Extract Tomcat ---
    - name: Extract Tomcat
      ansible.builtin.unarchive:
        src: "{{ download_url }}"
        dest: "{{ user_home }}"
        remote_src: yes
        extra_opts:
          - --strip-components=1
      when: not tomcat_status.stat.exists
      notify:
        - set tomcat ownership
        - set conf permissions

    - name: Flush handlers after extraction
      meta: flush_handlers

    - name: Set log directory permissions
      ansible.builtin.file:
        path: "{{ user_home }}/logs"
        state: directory
        recurse: yes
        mode: '0755'

  # --- 5. Service Configuration ---
    - name: Deploy tomcat systemd service
      ansible.builtin.template:
        src: tomcat.service.j2
        dest: /etc/systemd/system/tomcat.service
        
      notify:
        - reload systemd
        - restart tomcat

  # --- 6. Start and Enable Service ---
    - name: Enable and start Tomcat
      ansible.builtin.systemd:
        name: tomcat
        state: started
        enabled: yes

  handlers:
    - name: set tomcat ownership
      ansible.builtin.file:
        path: "{{ user_home }}"
        owner: "{{ user_name }}"
        group: "{{ user_name }}"
        recurse: yes

    - name: set conf permissions
      ansible.builtin.file:
        path: "{{ user_home }}/conf"
        recurse: yes
        mode: '0750'

    - name: reload systemd
      ansible.builtin.command: systemctl daemon-reexec

    - name: restart tomcat
      ansible.builtin.systemd:
        name: tomcat
        state: restarted
